#!/bin/bash

while true; do
	out=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}' | xargs)
	icon=" "
	if [[ $out == "yes" ]]; then
		icon=" "
	fi

	echo "$icon $(pactl get-sink-volume @DEFAULT_SINK@ | awk -F ' ' '{print $5}' | xargs)"

	sleep 0.1

done
