#!/bin/bash

while true; do
	out=$(amixer sget Master)
	icon=" "
	if [[ $(echo $out | awk -F '[][]' '{print $6}' | xargs) == "off" ]]; then
		icon=" "
	fi

	echo "$icon $(echo $out | awk -F '[][]' '{print $2}' | xargs)"

	sleep 0.1

done
