#!/bin/bash

intef=$(ip addr | awk '/state UP/ {gsub(":",""); print $2}')

while true; do
    dbm=$(iw dev "$intef" link | awk '/signal/ {print $2}')
    symbol="󰤯 "

    if [ $dbm -gt -67 ]; then
        symbol="󰤨 "
    elif [ $dbm -gt -70 ]; then
        symbol="󰤥 "
    elif [ $dbm -gt -80 ]; then
        symbol="󰤢 "
    elif [ $dbm -ge -90 ]; then
        symbol="󰤟 "
    fi

    echo "$symbol $dbm"
    sleep 0.5
done
