refresh_interval = 1000

[[modules]]
name = "window"
instance = "0"
format = "{title}"
html_escape = false

[modules.on_click]
Right = [
    "kill",
    "{pid}",
]
Left = [
    "swayr",
    "switch-to-urgent-or-lru-window",
]

[[modules]]
name = "sysinfo"
instance = "0"
format = "| CPU: {cpu_usage:{:3.1}}% | Mem: {mem_usage:{:3.1}}%"
html_escape = false

[modules.on_click]
Left = [
    "wezterm",
    "start",
    "--",
    "top",
]

[[modules]]
name = "battery"
instance = "0"
format = "| Bat: {state_of_charge:{:3.1}}%, {state}"
html_escape = false

[[modules]]
name = "alsa"
instance = "0"
format = "| Vol: {volume:{:3}}%{muted}"
html_escape = true

[modules.on_click]
Left = ["pavucontrol"]
Right = [
    "pactl",
    "set-sink-mute",
    "@DEFAULT_SINK@",
    "toggle",
]
WheelDown = [
    "pactl",
    "set-sink-volume",
    "@DEFAULT_SINK@",
    "-1%",
]
WheelUp = [
    "pactl",
    "set-sink-volume",
    "@DEFAULT_SINK@",
    "+1%",
]

[[modules]]
name = "date"
instance = "0"
format = "| %F %X"
html_escape = false
