#!/bin/bash
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

HISTCONTROL=ignoreboth
HISTSIZE=100000
HISTFILESIZE=200000
shopt -s histappend
shopt -s checkwinsize
shopt -s globstar
shopt -s autocd
shopt -s gnu_errfmt

alias grep="grep --color=auto"
alias python="python3"
alias pip="pip3"
alias ls="eza --color -F --group-directories-first"
alias la="ls -A"
alias ll="la --icons -lh"
alias tree="ll --tree --git-ignore"

function mkcd {
  command mkdir "$1" && cd "$1"
}

fastfetch
eval "$(starship init bash)"
